# Generated by Django 4.1 on 2022-08-23 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loss",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("cpf", models.CharField(max_length=11)),
                ("tipo_lavoura", models.CharField(max_length=50)),
                ("data_colheita", models.DateField()),
                (
                    "causa_da_perda",
                    models.CharField(
                        choices=[
                            ("CHUVA EXCESSIVA", "CHUVA EXCESSIVA"),
                            ("GEADA", "GEADA"),
                            ("GRANIZO", "GRANIZO"),
                            ("SECA", "SECA"),
                            ("VENDAVAL", "VENDAVAL"),
                            ("RAIO", "RAIO"),
                        ],
                        max_length=20,
                    ),
                ),
                ("localizacao", models.JSONField()),
            ],
        ),
    ]
