# Generated by Django 4.1 on 2022-08-25 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("losses", "0002_loss_criado_em"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loss",
            name="localizacao",
        ),
        migrations.AddField(
            model_name="loss",
            name="latitude",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loss",
            name="longitude",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ],
            ),
            preserve_default=False,
        ),
    ]
