# Generated by Django 4.1 on 2022-08-25 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("losses", "0003_remove_loss_localizacao_loss_latitude_loss_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loss",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="loss",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=9,
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ],
            ),
        ),
    ]
